### ISSUE TITLE
Ability to unsubscribe/stop reactive autoruns

### ISSUE THREAD

**Issue by markshust** [meteor-space/tracker-mobx-autorun#6]
I'm using this with react-komposer and all appears ok. However, there is no ability to stop listening for reactive updates. I'm not sure if the issue is with `trackerMobxAutorun`, `react-komposer`, or if there is a mobx-specific functionality I can use to accomplish this.

Example composer (utilizing `composeWithMobx`):

```
const onPropsChange = ({ context, syncData, unsyncData }, onData) => {
  const { Store } = context();
  const {
    categories,
    expanded,
    isDataSynced,
    rootCategories,
    rootCategoryId,
    rootCategoryName,
    subheader,
  } = Store.categories.list;
  const categoriesData = tackerMobxAutorun(syncData);

  if (! isDataSynced) {
    console.log('starting...');
    categoriesData.start();
  }

  if (subheader) {
    onData(null, {
      categories: categories.peek(),
      expanded: expanded.peek(),
      rootCategories: rootCategories.peek(),
      rootCategoryId,
      rootCategoryName,
      subheader,
    });
  }

  return () => {
    console.log('stopping...');
    categoriesData.stop();
    unsyncData();
  };
};
```

Some info:
- `isDataSynced` is a property that is true/false
- `syncData` is my reactive fn that listens for Meteor changes and updates mobx stores
- `unsyncData` is intended to reset mobx state values to default null/empty vals on unmount

The problem is that mobx stores updates synchronously, so when unsyncData is called, the composer runs immediately at the same time, which calls `categoriesData.start()` again -- leading to data that is never truly unsubscribed. My intentions on component unmount is to stop the autorun, and reset mobx stores to default null/empty vals.

**Comment by markshust** [comment]
I think the sample repo @darko-mijic created at (https://github.com/darko-mijic/mantra-sample-blog-app/blob/144bcf5999af3ae43d7f436c9ce8914e9de8406c/client/autoruns/comments.js for example) of starting autoruns on client start, and managing meteor subscription within the autorun reactively from mobx state is 🙌  -- going to close out this ticket in favor of that implementation.

**Comment by rhyslbw** [comment]
hey @markoshust, great to see you checking the package out! @darko-mijic and I spoke briefly about this and might be implementing a formal `subscriptions` API to abstract the implementation. It would be non-breaking, so this approach is great for now

**Comment by markshust** [comment]
@rhyslbw Cool.

A big change i'm making to the sample app above is ditching the triggers on the router. I generally like to follow kadira's approach to thinking routing is just for sending to components, then they do any work/actions.

What I did is setup a tracker/autorun that listens to FlowRouter path changes. I then store a result in a mobx state object. Then, within the trackerMobxAutorun function, I check whether I should run the subscription based on the value of the route in mobx state.

I'll have it up shortly, but thanks much for the sample app :)
